language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install zlib1g-dev
  - wget http://jaist.dl.sourceforge.net/boost/boost_1_54_0.tar.bz2
  - tar -xf boost_1_54_0.tar.bz2
  - ( cd boost_1_54_0  && ./bootstrap.sh --prefix=/usr --with-libraries=date_time,filesystem,exception,log,locale,random,regex,program_options,system,thread && sudo ./b2 -j2 link=static install ) > /dev/null

before_script:
  cmake . -DDEBUG=1

script:
    - make
    - ./avhttp http://www.boost.org/LICENSE_1_0.txt
    - ./avhttp https://github.com/blog
    - ./avhttp http://optimate.dl.sourceforge.net/project/avplayer/exe/release-2013-03-13.7z
    - cat ./multi_download.log

branches:
  only:
    - master
    - C++11
notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

