language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install -qq boost1.53
  - sudo apt-get install zlib1g-dev

before_script:
  cmake .

script:
    - make
    - ./avhttp http://www.boost.org/LICENSE_1_0.txt
    - ./avhttp https://github.com/blog
    - ./avhttp https://github.com/avplayer/avplayer/archive/master.zip
    - cat ./multi_download.log

branches:
  only:
    - master
notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

